# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    JiakeOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            KafkaConsortium:
                Organizations:
                    - *Nxia
                    - *Nmen
                    - *Dubai
                    - *Manager
    JiakeOrgsChannel:
        Consortium: KafkaConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Nxia
                - *Nmen
                - *Dubai
                - *Manager

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererMSP

        # ID to load the MSP definition as
        ID: OrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/hlc.com/msp

    - &Nxia
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: NxiaMSP

        # ID to load the MSP definition as
        ID: NxiaMSP

        MSPDir: crypto-config/peerOrganizations/nxia.hlc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 192.168.0.231
              Port: 7051

    - &Nmen
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: NmenMSP

        # ID to load the MSP definition as
        ID: NmenMSP

        MSPDir: crypto-config/peerOrganizations/nmen.hlc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 192.168.0.232
              Port: 7051
    - &Dubai
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: DubaiMSP

        # ID to load the MSP definition as
        ID: DubaiMSP

        MSPDir: crypto-config/peerOrganizations/dubai.hlc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 192.168.0.234
              Port: 7051
    - &Manager
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ManagerMSP

        # ID to load the MSP definition as
        ID: ManagerMSP

        MSPDir: crypto-config/peerOrganizations/manager.hlc.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: 192.168.0.233
              Port: 7051
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: kafka

    Addresses:
        - 192.168.0.233:7050
        - 192.168.0.233:8050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 4s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - kafka0.hlc.com:9092
            - kafka1.hlc.com:9092
            - kafka2.hlc.com:9092
            - kafka3.hlc.com:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
