#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  default:

services:

  ca.manager.hlc.com:
    image: hyperledger/fabric-ca
    privileged: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manager.hlc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/caf7630756e5d81a00ac08234d7686a6aa2e5039838fe7c01d44f333fc05bd58_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manager.hlc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/caf7630756e5d81a00ac08234d7686a6aa2e5039838fe7c01d44f333fc05bd58_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerManager
    networks:
      - default

  orderer1.hlc.com:
    container_name: orderer1.hlc.com
    image: hyperledger/fabric-orderer
    privileged: true
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=3s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=50s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel:/etc/hyperledger/configtx
      - ./channel/crypto-config:/etc/hyperledger/fabric/crypto
      - ./channel/crypto-config/ordererOrganizations/hlc.com/orderers/orderer1.hlc.com/:/etc/hyperledger/crypto/orderer
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/:/etc/hyperledger/crypto/peerNxia
      - ./channel/crypto-config/peerOrganizations/nmen.hlc.com/peers/peer0.nmen.hlc.com/:/etc/hyperledger/crypto/peerNmen
      - ./channel/crypto-config/peerOrganizations/dubai.hlc.com/peers/peer0.dubai.hlc.com/:/etc/hyperledger/crypto/peerDubai
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer0.manager.hlc.com/:/etc/hyperledger/crypto/peerManager
    depends_on:
      - kafka0.hlc.com
      - kafka1.hlc.com
      - kafka2.hlc.com
      - kafka3.hlc.com
    networks:
      - default

  orderer2.hlc.com:
    container_name: orderer2.hlc.com
    image: hyperledger/fabric-orderer
    privileged: true
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=3s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=50s
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 8050:8050
    volumes:
      - ./channel:/etc/hyperledger/configtx
      - ./channel/crypto-config:/etc/hyperledger/fabric/crypto
      - ./channel/crypto-config/ordererOrganizations/hlc.com/orderers/orderer2.hlc.com/:/etc/hyperledger/crypto/orderer
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/:/etc/hyperledger/crypto/peerNxia
      - ./channel/crypto-config/peerOrganizations/nmen.hlc.com/peers/peer0.nmen.hlc.com/:/etc/hyperledger/crypto/peerNmen
      - ./channel/crypto-config/peerOrganizations/dubai.hlc.com/peers/peer0.dubai.hlc.com/:/etc/hyperledger/crypto/peerDubai
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer0.manager.hlc.com/:/etc/hyperledger/crypto/peerManager
    depends_on:
      - kafka0.hlc.com
      - kafka1.hlc.com
      - kafka2.hlc.com
      - kafka3.hlc.com
    networks:
      - default

  zookeeper0.hlc.com:
    container_name: zookeeper0.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  zookeeper1.hlc.com:
    container_name: zookeeper1.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888

  zookeeper2.hlc.com:
    container_name: zookeeper2.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888

  kafka0.hlc.com:
    container_name: kafka0.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    depends_on:
      - zookeeper0.hlc.com
      - zookeeper1.hlc.com
      - zookeeper2.hlc.com
    ports:
      - 9092:9092
      - 9093:9093

  kafka1.hlc.com:
    container_name: kafka1.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    depends_on:
      - zookeeper0.hlc.com
      - zookeeper1.hlc.com
      - zookeeper2.hlc.com
    ports:
      - 10092:9092
      - 10093:9093

  kafka2.hlc.com:
    container_name: kafka2.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    depends_on:
      - zookeeper0.hlc.com
      - zookeeper1.hlc.com
      - zookeeper2.hlc.com
    ports:
      - 11092:9092
      - 11093:9093

  kafka3.hlc.com:
    container_name: kafka3.hlc.com
    extends:
      file: base/kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    depends_on:
      - zookeeper0.hlc.com
      - zookeeper1.hlc.com
      - zookeeper2.hlc.com
    ports:
      - 12092:9092
      - 12093:9093

  peer0.manager.hlc.com:
    container_name: peer0.manager.hlc.com
    privileged: true
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.manager.hlc.com
      - CORE_PEER_LOCALMSPID=ManagerMSP
      - CORE_PEER_ADDRESS=peer0.manager.hlc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.manager.hlc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.manager.hlc.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbManager:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchadmin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer0.manager.hlc.com/:/etc/hyperledger/crypto/peer
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer0.manager.hlc.com/msp:/etc/hyperledger/fabric/msp
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer0.manager.hlc.com/tls:/etc/hyperledger/fabric/tls
      # - ./dataStorage/transfer/peer1/:/var/hyperledger/production/
    depends_on:
      - orderer1.hlc.com
      - orderer2.hlc.com
      - couchdbManager
    networks:
      - default

  peer1.manager.hlc.com:
    container_name: peer1.manager.hlc.com
    privileged: true
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.manager.hlc.com
      - CORE_PEER_LOCALMSPID=ManagerMSP
      - CORE_PEER_ADDRESS=peer1.manager.hlc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manager.hlc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.manager.hlc.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer1.manager.hlc.com/:/etc/hyperledger/crypto/peer
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer1.manager.hlc.com/msp:/etc/hyperledger/fabric/msp
      - ./channel/crypto-config/peerOrganizations/manager.hlc.com/peers/peer1.manager.hlc.com/tls:/etc/hyperledger/fabric/tls
        # - ./dataStorage/transfer/peer2/:/var/hyperledger/production/
    depends_on:
      - orderer1.hlc.com
      - orderer2.hlc.com
    networks:
      - default

  couchdbManager:
    container_name: couchdbManager
    image: hyperledger/fabric-couchdb:latest
    privileged: true
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=couchadmin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - default

  # cli:
  #     container_name: cli
  #     image: hyperledger/fabric-tools
  #     tty: true
  #     environment:
  #       - GOPATH=/opt/gopath
  #       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #       - CORE_LOGGING_LEVEL=DEBUG
  #       - CORE_PEER_ID=cli
  #       - CORE_PEER_ADDRESS=peer0.nxia.hlc.com:7051
  #       - CORE_PEER_LOCALMSPID=NxiaMSP
  #       - CORE_PEER_TLS_ENABLED=true
  #       - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/server.crt
  #       - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/server.key
  #       - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/ca.crt
  #       - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/users/Admin@nxia.hlc.com/msp
  #     working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #     # command: /bin/bash -c './scripts/script.sh jiakechannel ${DELAY}; sleep 60'
  #     volumes:
  #         - /var/run/:/host/var/run/
  #         # - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #         # - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #         # - ./cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/
  #     depends_on:
  #       - orderer1.hlc.com
  #       - orderer2.hlc.com
  #       - peer0.nxia.hlc.com
  #       - peer1.nxia.hlc.com
  #       - peer0.nmen.hlc.com
  #       - peer1.nmen.hlc.com
  #       - peer0.dubai.hlc.com
  #       - peer1.dubai.hlc.com
  #       - peer0.manager.hlc.com
  #       - peer1.manager.hlc.com
  #     networks:
  #       - default      