#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

networks:
  default:

services:

  ca.nxia.hlc.com:
    image: hyperledger/fabric-ca
    privileged: true
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nxia.hlc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b21b6965413ee4d5313a70c1262db52ad017fb53f3ba737b25ebad4b605492c2_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nxia.hlc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b21b6965413ee4d5313a70c1262db52ad017fb53f3ba737b25ebad4b605492c2_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerNingXia
    networks:
      - default

  peer0.nxia.hlc.com:
    container_name: peer0.nxia.hlc.com
    privileged: true
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nxia.hlc.com
      - CORE_PEER_LOCALMSPID=NxiaMSP
      - CORE_PEER_ADDRESS=peer0.nxia.hlc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nxia.hlc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nxia.hlc.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbNxia:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchadmin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/:/etc/hyperledger/crypto/peer
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/msp:/etc/hyperledger/fabric/msp
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls:/etc/hyperledger/fabric/tls
        # - ./dataStorage/jiake/peer1/:/var/hyperledger/production/
    depends_on:
      - couchdbNxia
    networks:
      - default

  peer1.nxia.hlc.com:
    container_name: peer1.nxia.hlc.com
    privileged: true
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.nxia.hlc.com
      - CORE_PEER_LOCALMSPID=NxiaMSP
      - CORE_PEER_ADDRESS=peer1.nxia.hlc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nxia.hlc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nxia.hlc.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer1.nxia.hlc.com/:/etc/hyperledger/crypto/peer
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer1.nxia.hlc.com/msp:/etc/hyperledger/fabric/msp
      - ./channel/crypto-config/peerOrganizations/nxia.hlc.com/peers/peer1.nxia.hlc.com/tls:/etc/hyperledger/fabric/tls
        # - ./dataStorage/jiake/peer2/:/var/hyperledger/production/
    networks:
      - default

  couchdbNxia:
    container_name: couchdbNxia
    image: hyperledger/fabric-couchdb:latest
    privileged: true
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=couchadmin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - default

  # cli:
  #     container_name: cli
  #     image: hyperledger/fabric-tools
  #     tty: true
  #     environment:
  #       - GOPATH=/opt/gopath
  #       - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #       - CORE_LOGGING_LEVEL=DEBUG
  #       - CORE_PEER_ID=cli
  #       - CORE_PEER_ADDRESS=peer0.nxia.hlc.com:7051
  #       - CORE_PEER_LOCALMSPID=NxiaMSP
  #       - CORE_PEER_TLS_ENABLED=true
  #       - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/server.crt
  #       - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/server.key
  #       - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/peers/peer0.nxia.hlc.com/tls/ca.crt
  #       - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nxia.hlc.com/users/Admin@nxia.hlc.com/msp
  #     working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #     # command: /bin/bash -c './scripts/script.sh jiakechannel ${DELAY}; sleep 60'
  #     volumes:
  #         - /var/run/:/host/var/run/
  #         # - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #         # - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #         # - ./cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/
  #     depends_on:
  #       - peer0.nxia.hlc.com
  #       - peer1.nxia.hlc.com
  #     networks:
  #       - default      